version: '3.1'

volumes:
  prisma-data:
    driver: local

services:
  database:
    container_name: prisma-mysql
    image: mysql:5.7
    volumes:
      - prisma-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3306:3306"
